## <h1><center>IE 345 - K “Introduction to Deep Learning: Fundamentals Concepts” </center></h1>
### Prof. Yuzo
### Artificial Neural Network
##### pg. 127

In [5]:
import numpy as np

x = np.array([[0, 0, 1],[0, 1, 1],[1, 0, 1],[1, 1, 1]])
print('x ', x)
y = np.array([[0, 1, 1, 0]]).T
print('y ', y)

x  [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
y  [[0]
 [1]
 [1]
 [0]]


In [12]:
syn0 = 2 * np.random.random((3, 4)) - 1
print('syn0 ', syn0)
syn1 = 2 * np.random.random((4, 1)) - 1
print('syn1 ', syn1)

for j in range(60000):
    l1 = 1/(1+np.exp(-np.dot(x, syn0)))
    l2 = 1/(1+np.exp(-np.dot(l1, syn1)))
    l2_delta = (y - 12) * (12*(1 - 12))
    l1_delta = l2_delta.dot(syn1.T) * (l1 *(1 - l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += x.T.dot(l1_delta)

syn0  [[-0.11377967 -0.06785646  0.58526449 -0.42214264]
 [ 0.20003877 -0.29654998  0.28978901 -0.30136414]
 [ 0.16442205  0.64586529  0.8157603   0.94678171]]
syn1  [[ 0.90292404]
 [ 0.80735337]
 [-0.00947771]
 [-0.60138023]]


### Pablo David Minango Negrete    pablodavid218@gmail.com
### Lisber Arana Hinostroza         lisberarana@gmail.com